/* ============================================================================
   DEEP LEARNING — LECTURE 3 QUIZ DATA
   ----------------------------------------------------------------------------
   Ten questions built strictly from the Topic-3 slides (1–16). Kept out of
   labs2.jsx so the page shell can show a live score on the Quiz tab.
   ========================================================================== */

export const QUIZ = [
  {
    q: 'Biological neurons in the visual cortex respond to specific patterns in…',
    opts: [
      'small regions of the visual field called receptive fields',
      'the entire visual field at once',
      'only the very centre of the visual field',
      'regions that are randomly reassigned every second',
    ],
    ans: 0,
    why: 'Hubel (1959) and Hubel & Wiesel (1959) showed neurons respond to specific patterns in small regions called receptive fields — and as the signal moves through consecutive brain modules, neurons respond to more complex patterns in larger receptive fields.',
    slide: 4,
  },
  {
    q: 'The 1980 model that gradually evolved into convolutional neural networks is…',
    opts: [
      'the perceptron',
      'the neocognitron',
      'LeNet-5',
      'the Boltzmann machine',
    ],
    ans: 1,
    why: 'Fukushima’s neocognitron (1980), inspired by the visual-cortex studies, gradually evolved into what we now call CNNs. And CNNs aren’t restricted to vision — they also work for voice recognition and NLP.',
    slide: 5,
  },
  {
    q: 'Which classic 3×3 filter detects vertical edges?',
    opts: [
      'the uniform averaging filter (all 1/9)',
      'the Laplacian operator',
      'Sobel-x',
      'Sobel-y',
    ],
    ans: 2,
    why: 'Sobel-x (columns −1/−2/−1, 0, +1/+2/+1) responds to horizontal intensity change, i.e. vertical edges. Sobel-y detects horizontal edges, the uniform filter smooths, and the Laplacian is a 2nd-derivative filter.',
    slide: 6,
  },
  {
    q: 'Filter sizes are usually chosen to be…',
    opts: [
      'even (4×4, 6×6, …)',
      'odd (3×3, 5×5, 7×7, …)',
      'as large as the input image',
      'always exactly 3×3 — nothing else is legal',
    ],
    ans: 1,
    why: 'Larger filters can be defined, but odd sizes are usually preferred — an odd filter has a well-defined centre pixel to sit on.',
    slide: 6,
  },
  {
    q: 'Neurons in the first convolutional layer are connected to…',
    opts: [
      'every single pixel of the input image',
      'only the pixels inside their receptive field',
      'exactly one input pixel each',
      'a random subset of pixels re-drawn each epoch',
    ],
    ans: 1,
    why: 'That is the defining trick of the convolutional layer: local receptive fields. The network concentrates on low-level features in the first hidden layer, then assembles them into higher-level features in the next, and so on.',
    slide: 7,
  },
  {
    q: 'One 3×3 filter convolved over a 200×300 feature map needs how many trainable parameters?',
    opts: ['60,000', '9', '10', '200 × 300'],
    ans: 2,
    why: 'Weight sharing: the 9 weights of W plus 1 bias — regardless of the numbers of rows and columns of the feature map. Every neuron in the map reuses the same 10 parameters.',
    slide: 8,
  },
  {
    q: 'With strides s_h and s_w, the output neuron in row i, column j connects to input rows…',
    opts: [
      'i·s_h to i·s_h + f_h − 1',
      'i to i + f_h',
      'i − s_h to i + s_h',
      'f_h·i to f_h·i + s_h',
    ],
    ans: 0,
    why: 'Rows i·s_h to i·s_h + f_h − 1 and columns j·s_w to j·s_w + f_w − 1. The stride is the distance between two consecutive receptive fields — stride 2 in both directions connects a 5×7 input (plus zero padding) to a 3×4 layer.',
    slide: 9,
  },
  {
    q: 'The slide-10 vertical-line filter is a 7×7 matrix that is…',
    opts: [
      'full of 1s except for a central column of 0s',
      'full of 0s except for a central column of 1s',
      'alternating +1 and −1 everywhere',
      'random values, to be learned during training',
    ],
    ans: 1,
    why: 'All 0s except the central column of 1s: neurons using these weights ignore everything in their receptive field except the central vertical line (everything else is multiplied by 0).',
    slide: 10,
  },
  {
    q: 'A convolutional layer with n filters produces…',
    opts: [
      'one feature map, whatever n is',
      'n feature maps — its output has n channels',
      'n² feature maps',
      'a number of maps that depends on the input size',
    ],
    ans: 1,
    why: 'Each feature map is generated by convolving one filter with the layer’s input, so n filters → n feature maps → n output channels. Each filter must itself have N_channels channels for the convolution to be legal: z_k = b_k + Σ_c x_c ∗ f_c,k.',
    slide: 13,
  },
  {
    q: 'In Keras, the weights (all the filters) of a convolutional layer are a 4D tensor of shape…',
    opts: [
      '[f_h, f_w, f_c, f_n]',
      '[f_n, f_c, f_h, f_w]',
      '[batch size, height, width, channels]',
      '[f_h, f_w, f_n]',
    ],
    ans: 0,
    why: 'Filter height, filter width, filter channels (must equal the input’s channels), number of filters. The biases are simply a 1D tensor of shape [f_n] — one bias per filter.',
    slide: 16,
  },
];

// Correct-answer count for a { questionIndex: optionIndex } answer map.
export function scoreOf(answers) {
  return Object.entries(answers).filter(([i, a]) => QUIZ[Number(i)]?.ans === a).length;
}
